//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TimeEntities : DbContext
    {
        public TimeEntities()
            : base("name=TimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int ModuleCreationOrUpdation(Nullable<int> mODULE_ID, string mODULE_CODE, string mODULE_NAME, Nullable<int> mODULE_CREDITS, Nullable<int> mODULE_HOURS_WEEK, Nullable<int> mODULE_WEEKS, Nullable<int> mODULE_HOURS_SPENT, Nullable<System.DateTime> mODULE_START, Nullable<int> sELF_STUDY, Nullable<int> wEEK_STUDY_HOURS_REMAINING, string uSERNAME)
        {
            var mODULE_IDParameter = mODULE_ID.HasValue ?
                new ObjectParameter("MODULE_ID", mODULE_ID) :
                new ObjectParameter("MODULE_ID", typeof(int));
    
            var mODULE_CODEParameter = mODULE_CODE != null ?
                new ObjectParameter("MODULE_CODE", mODULE_CODE) :
                new ObjectParameter("MODULE_CODE", typeof(string));
    
            var mODULE_NAMEParameter = mODULE_NAME != null ?
                new ObjectParameter("MODULE_NAME", mODULE_NAME) :
                new ObjectParameter("MODULE_NAME", typeof(string));
    
            var mODULE_CREDITSParameter = mODULE_CREDITS.HasValue ?
                new ObjectParameter("MODULE_CREDITS", mODULE_CREDITS) :
                new ObjectParameter("MODULE_CREDITS", typeof(int));
    
            var mODULE_HOURS_WEEKParameter = mODULE_HOURS_WEEK.HasValue ?
                new ObjectParameter("MODULE_HOURS_WEEK", mODULE_HOURS_WEEK) :
                new ObjectParameter("MODULE_HOURS_WEEK", typeof(int));
    
            var mODULE_WEEKSParameter = mODULE_WEEKS.HasValue ?
                new ObjectParameter("MODULE_WEEKS", mODULE_WEEKS) :
                new ObjectParameter("MODULE_WEEKS", typeof(int));
    
            var mODULE_HOURS_SPENTParameter = mODULE_HOURS_SPENT.HasValue ?
                new ObjectParameter("MODULE_HOURS_SPENT", mODULE_HOURS_SPENT) :
                new ObjectParameter("MODULE_HOURS_SPENT", typeof(int));
    
            var mODULE_STARTParameter = mODULE_START.HasValue ?
                new ObjectParameter("MODULE_START", mODULE_START) :
                new ObjectParameter("MODULE_START", typeof(System.DateTime));
    
            var sELF_STUDYParameter = sELF_STUDY.HasValue ?
                new ObjectParameter("SELF_STUDY", sELF_STUDY) :
                new ObjectParameter("SELF_STUDY", typeof(int));
    
            var wEEK_STUDY_HOURS_REMAININGParameter = wEEK_STUDY_HOURS_REMAINING.HasValue ?
                new ObjectParameter("WEEK_STUDY_HOURS_REMAINING", wEEK_STUDY_HOURS_REMAINING) :
                new ObjectParameter("WEEK_STUDY_HOURS_REMAINING", typeof(int));
    
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModuleCreationOrUpdation", mODULE_IDParameter, mODULE_CODEParameter, mODULE_NAMEParameter, mODULE_CREDITSParameter, mODULE_HOURS_WEEKParameter, mODULE_WEEKSParameter, mODULE_HOURS_SPENTParameter, mODULE_STARTParameter, sELF_STUDYParameter, wEEK_STUDY_HOURS_REMAININGParameter, uSERNAMEParameter);
        }
    
        public virtual int ModuleDelete(Nullable<int> mODULE_ID)
        {
            var mODULE_IDParameter = mODULE_ID.HasValue ?
                new ObjectParameter("MODULE_ID", mODULE_ID) :
                new ObjectParameter("MODULE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModuleDelete", mODULE_IDParameter);
        }
    
        public virtual ObjectResult<ModuleIView_Result> ModuleIView(Nullable<int> mODULE_ID)
        {
            var mODULE_IDParameter = mODULE_ID.HasValue ?
                new ObjectParameter("MODULE_ID", mODULE_ID) :
                new ObjectParameter("MODULE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ModuleIView_Result>("ModuleIView", mODULE_IDParameter);
        }
    
        public virtual ObjectResult<ModuleViewAll_Result> ModuleViewAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ModuleViewAll_Result>("ModuleViewAll");
        }
    
        public virtual int Tj_Userlogin(string uSERNAME, string password, string fIRST_NAME, string lAST_NAME)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tj_Userlogin", uSERNAMEParameter, passwordParameter, fIRST_NAMEParameter, lAST_NAMEParameter);
        }
    
        public virtual int Tj_UserModules(string mODULE_CODE, string mODULE_NAME, Nullable<int> mODULE_CREDITS, Nullable<int> mODULE_HOURS_WEEK, Nullable<int> mODULE_WEEKS, Nullable<int> mODULE_HOURS_SPENT, Nullable<System.DateTime> mODULE_START, Nullable<int> sELF_STUDY, Nullable<int> wEEK_STUDY_HOURS_REMAINING, string uSERNAME)
        {
            var mODULE_CODEParameter = mODULE_CODE != null ?
                new ObjectParameter("MODULE_CODE", mODULE_CODE) :
                new ObjectParameter("MODULE_CODE", typeof(string));
    
            var mODULE_NAMEParameter = mODULE_NAME != null ?
                new ObjectParameter("MODULE_NAME", mODULE_NAME) :
                new ObjectParameter("MODULE_NAME", typeof(string));
    
            var mODULE_CREDITSParameter = mODULE_CREDITS.HasValue ?
                new ObjectParameter("MODULE_CREDITS", mODULE_CREDITS) :
                new ObjectParameter("MODULE_CREDITS", typeof(int));
    
            var mODULE_HOURS_WEEKParameter = mODULE_HOURS_WEEK.HasValue ?
                new ObjectParameter("MODULE_HOURS_WEEK", mODULE_HOURS_WEEK) :
                new ObjectParameter("MODULE_HOURS_WEEK", typeof(int));
    
            var mODULE_WEEKSParameter = mODULE_WEEKS.HasValue ?
                new ObjectParameter("MODULE_WEEKS", mODULE_WEEKS) :
                new ObjectParameter("MODULE_WEEKS", typeof(int));
    
            var mODULE_HOURS_SPENTParameter = mODULE_HOURS_SPENT.HasValue ?
                new ObjectParameter("MODULE_HOURS_SPENT", mODULE_HOURS_SPENT) :
                new ObjectParameter("MODULE_HOURS_SPENT", typeof(int));
    
            var mODULE_STARTParameter = mODULE_START.HasValue ?
                new ObjectParameter("MODULE_START", mODULE_START) :
                new ObjectParameter("MODULE_START", typeof(System.DateTime));
    
            var sELF_STUDYParameter = sELF_STUDY.HasValue ?
                new ObjectParameter("SELF_STUDY", sELF_STUDY) :
                new ObjectParameter("SELF_STUDY", typeof(int));
    
            var wEEK_STUDY_HOURS_REMAININGParameter = wEEK_STUDY_HOURS_REMAINING.HasValue ?
                new ObjectParameter("WEEK_STUDY_HOURS_REMAINING", wEEK_STUDY_HOURS_REMAINING) :
                new ObjectParameter("WEEK_STUDY_HOURS_REMAINING", typeof(int));
    
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tj_UserModules", mODULE_CODEParameter, mODULE_NAMEParameter, mODULE_CREDITSParameter, mODULE_HOURS_WEEKParameter, mODULE_WEEKSParameter, mODULE_HOURS_SPENTParameter, mODULE_STARTParameter, sELF_STUDYParameter, wEEK_STUDY_HOURS_REMAININGParameter, uSERNAMEParameter);
        }
    }
}
