//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleCode { get; set; }
        public int ModuleCredits { get; set; }
        public int ModuleHrsPerWeek { get; set; }
        public int ModuleWeeks { get; set; }
        public int HrsSpent { get; set; }
        public System.DateTime ModuleStartDate { get; set; }
        public int selfStudyHours { get; set; }
        public int RemainingHours { get; set; }
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
